### ISSUE TITLE
Filter projects by magpie user permissions

### ISSUE THREAD

**Issue by Renaud009** [Ouranosinc/PAVICS-project-api#10]
**Changes to project model**
- magpieId (string, optional)
- owner (string required), magpie user_name who created the project
- remove researcher model and relations

**GET Projects/** will trigger two kind of actions depending on cookie:
- if admin (magpie call), return all projects
- if not, call magpie and list ressources of type "project" for a given user

**CREATE Projects/**
- Determine current user id
- Create magpie resource (with admin token)
- Store magpie resource id for this project
- Create resource permission for the user (with admin token)

**DELETE PROJECT: Projects/<id>**
- Delete magpie resource (using the mapie resource id)
- Delete permissions (should automatically done by magpie?)

**PUT/PATCH Projects/<id>**
- Shouldn't affect any magpie permission at this point

**Comment by fmigneault** [comment]
@Renaud009 ready to be tested on colibri
